import type { Account } from '@/entity-types/account'

export const accounts: Account[] = [
  // BCM Accounts
  { id: 'acc-001', name: 'NOMURA', business_unit_id: 'bu-001' },
  { id: 'acc-002', name: 'HSBC - BFS', business_unit_id: 'bu-001' },
  { id: 'acc-003', name: 'Mercedes Benz Mobility', business_unit_id: 'bu-001' },
  { id: 'acc-004', name: 'Amazon - BCM', business_unit_id: 'bu-001' },
  {
    id: 'acc-005',
    name: 'Pacific Investment Management Company',
    business_unit_id: 'bu-001',
  },

  // Coke_Ecosystem_Unilever Accounts
  {
    id: 'acc-006',
    name: 'Coca Cola Bottlers Japan',
    business_unit_id: 'bu-002',
  },
  { id: 'acc-007', name: 'THE COCA COLA COMPANY', business_unit_id: 'bu-002' },
  { id: 'acc-008', name: 'UNILEVER', business_unit_id: 'bu-002' },

  // Consumer_Goods Accounts
  { id: 'acc-009', name: 'Archer Daniels Midland', business_unit_id: 'bu-003' },
  { id: 'acc-010', name: 'AVON', business_unit_id: 'bu-003' },
  { id: 'acc-011', name: 'BEIERSDORF', business_unit_id: 'bu-003' },
  { id: 'acc-012', name: 'CARLSBERG', business_unit_id: 'bu-003' },
  { id: 'acc-013', name: 'DANONE', business_unit_id: 'bu-003' },
  {
    id: 'acc-014',
    name: 'Estee Lauder Group of Companies',
    business_unit_id: 'bu-003',
  },
  { id: 'acc-015', name: 'Glanbia', business_unit_id: 'bu-003' },
  { id: 'acc-016', name: 'Haleon', business_unit_id: 'bu-003' },
  { id: 'acc-017', name: 'HUNTSMAN INTERNATIONAL', business_unit_id: 'bu-003' },
  { id: 'acc-018', name: 'MARS', business_unit_id: 'bu-003' },
  { id: 'acc-019', name: 'Mattel', business_unit_id: 'bu-003' },
  { id: 'acc-020', name: 'MONDELEZ INTERNATIONAL', business_unit_id: 'bu-003' },
  {
    id: 'acc-021',
    name: 'RICH PRODUCTS CORPORATION',
    business_unit_id: 'bu-003',
  },
  { id: 'acc-022', name: 'Roquette', business_unit_id: 'bu-003' },

  // Corporate Accounts
  { id: 'acc-023', name: 'Support', business_unit_id: 'bu-004' },

  // Healthcare Accounts
  { id: 'acc-024', name: 'BUPA', business_unit_id: 'bu-005' },
  { id: 'acc-025', name: 'CIGNA', business_unit_id: 'bu-005' },

  // Hardware Accounts
  { id: 'acc-026', name: 'BIPROGY', business_unit_id: 'bu-006' },
  { id: 'acc-027', name: 'HYATT', business_unit_id: 'bu-006' },
  { id: 'acc-028', name: 'INGENICO', business_unit_id: 'bu-006' },
  { id: 'acc-029', name: 'JTB', business_unit_id: 'bu-006' },
  { id: 'acc-030', name: 'Konica Minolta', business_unit_id: 'bu-006' },
  { id: 'acc-031', name: 'LAM Research', business_unit_id: 'bu-006' },
  { id: 'acc-032', name: 'Logisteed', business_unit_id: 'bu-006' },
  { id: 'acc-033', name: 'NAGASE', business_unit_id: 'bu-006' },
  { id: 'acc-034', name: 'NTT Ltd', business_unit_id: 'bu-006' },
  { id: 'acc-035', name: 'PANASONIC', business_unit_id: 'bu-006' },
  { id: 'acc-036', name: 'RECRUIT', business_unit_id: 'bu-006' },
  { id: 'acc-037', name: 'Skyworks Solutions', business_unit_id: 'bu-006' },
  { id: 'acc-038', name: 'Vantec Corporation', business_unit_id: 'bu-006' },

  // Software Accounts
  { id: 'acc-039', name: 'AMAZON', business_unit_id: 'bu-007' },
  { id: 'acc-040', name: 'Dentsu International', business_unit_id: 'bu-007' },
  { id: 'acc-041', name: 'EBAY', business_unit_id: 'bu-007' },
  { id: 'acc-042', name: 'EPIC Games', business_unit_id: 'bu-007' },
  { id: 'acc-043', name: 'GOOGLE', business_unit_id: 'bu-007' },
  { id: 'acc-044', name: 'McGraw Hill Education', business_unit_id: 'bu-007' },
  { id: 'acc-045', name: 'NBCU', business_unit_id: 'bu-007' },
  { id: 'acc-046', name: 'REED ELSEVIER', business_unit_id: 'bu-007' },
  { id: 'acc-047', name: 'THOMSON REUTERS', business_unit_id: 'bu-007' },
  { id: 'acc-048', name: 'Youtube', business_unit_id: 'bu-007' },

  // Insurance Accounts
  { id: 'acc-049', name: 'AMLIN', business_unit_id: 'bu-008' },
  { id: 'acc-050', name: 'AIG', business_unit_id: 'bu-008' },
  { id: 'acc-051', name: 'AXA', business_unit_id: 'bu-008' },
  { id: 'acc-052', name: 'Bolttech', business_unit_id: 'bu-008' },
  {
    id: 'acc-053',
    name: 'CHUBB GROUP OF INSURANCE COMPANIES',
    business_unit_id: 'bu-008',
  },
  { id: 'acc-054', name: 'HSBC Insurance', business_unit_id: 'bu-008' },
  {
    id: 'acc-055',
    name: 'Unidentified - P&C Insurance - Enterprise',
    business_unit_id: 'bu-008',
  },

  // Lifesciences Accounts
  { id: 'acc-056', name: 'ABBOTT', business_unit_id: 'bu-009' },
  { id: 'acc-057', name: 'AMGEN', business_unit_id: 'bu-009' },
  { id: 'acc-058', name: 'ASTELLAS', business_unit_id: 'bu-009' },
  { id: 'acc-059', name: 'ASTRAZENECA', business_unit_id: 'bu-009' },
  { id: 'acc-060', name: 'BAXTER', business_unit_id: 'bu-009' },
  {
    id: 'acc-061',
    name: 'BECTON DICKINSON AND COMPANY',
    business_unit_id: 'bu-009',
  },
  { id: 'acc-062', name: 'Cytiva', business_unit_id: 'bu-009' },
  { id: 'acc-063', name: 'Dentsply Sirona', business_unit_id: 'bu-009' },
  { id: 'acc-064', name: 'Embecta', business_unit_id: 'bu-009' },
  { id: 'acc-065', name: 'Evident Scientific', business_unit_id: 'bu-009' },
  {
    id: 'acc-066',
    name: 'Ferring Pharmaceuticals',
    business_unit_id: 'bu-009',
  },
  { id: 'acc-067', name: 'GLAXOSMITHKLINE', business_unit_id: 'bu-009' },
  { id: 'acc-068', name: 'MERCK', business_unit_id: 'bu-009' },
  { id: 'acc-069', name: 'Organon & Co', business_unit_id: 'bu-009' },
  { id: 'acc-070', name: 'PFIZER', business_unit_id: 'bu-009' },
  { id: 'acc-071', name: 'UCB', business_unit_id: 'bu-009' },
  { id: 'acc-072', name: 'Viatris', business_unit_id: 'bu-009' },
  { id: 'acc-073', name: 'Zimmer Biomet', business_unit_id: 'bu-009' },

  // Manufacturing Accounts
  { id: 'acc-074', name: '3M', business_unit_id: 'bu-010' },
  { id: 'acc-075', name: 'ABB', business_unit_id: 'bu-010' },
  { id: 'acc-076', name: 'Baker Hughes HQ', business_unit_id: 'bu-010' },
  { id: 'acc-077', name: 'Barnes', business_unit_id: 'bu-010' },
  { id: 'acc-078', name: 'EDF GE Nuclear', business_unit_id: 'bu-010' },
  { id: 'acc-079', name: 'Element Solutions', business_unit_id: 'bu-010' },
  { id: 'acc-080', name: 'Envalior', business_unit_id: 'bu-010' },
  { id: 'acc-081', name: 'FLSmidth & Co', business_unit_id: 'bu-010' },
  { id: 'acc-082', name: 'Garrett Motion', business_unit_id: 'bu-010' },
  { id: 'acc-083', name: 'Geely Global', business_unit_id: 'bu-010' },
  { id: 'acc-084', name: 'HONDA', business_unit_id: 'bu-010' },
  { id: 'acc-085', name: 'HONEYWELL', business_unit_id: 'bu-010' },
  { id: 'acc-086', name: 'Hydraulic Technologies', business_unit_id: 'bu-010' },
  { id: 'acc-087', name: 'Indorama ventures', business_unit_id: 'bu-010' },
  { id: 'acc-088', name: 'Johnson Matthey', business_unit_id: 'bu-010' },
  { id: 'acc-089', name: 'LIXIL', business_unit_id: 'bu-010' },
  { id: 'acc-090', name: 'Marelli', business_unit_id: 'bu-010' },
  { id: 'acc-091', name: 'MAZDA', business_unit_id: 'bu-010' },
  { id: 'acc-092', name: 'MITSUBISHI MOTORS', business_unit_id: 'bu-010' },
  { id: 'acc-093', name: 'MITSUI CHEMICALS', business_unit_id: 'bu-010' },
  { id: 'acc-094', name: 'Mosaic', business_unit_id: 'bu-010' },
  { id: 'acc-095', name: 'NEXANS', business_unit_id: 'bu-010' },
  { id: 'acc-096', name: 'NISSAN', business_unit_id: 'bu-010' },
  { id: 'acc-097', name: 'NOVELIS', business_unit_id: 'bu-010' },
  { id: 'acc-098', name: 'Oil Field Services', business_unit_id: 'bu-010' },
  { id: 'acc-099', name: 'Olympus America', business_unit_id: 'bu-010' },
  {
    id: 'acc-100',
    name: 'OTIS ELEVATOR CO. PTY LTD.',
    business_unit_id: 'bu-010',
  },
  { id: 'acc-101', name: 'Owens Corning', business_unit_id: 'bu-010' },
  { id: 'acc-102', name: 'Proterial', business_unit_id: 'bu-010' },
  { id: 'acc-103', name: 'Raytheon Technologies', business_unit_id: 'bu-010' },
  { id: 'acc-104', name: 'SABIC', business_unit_id: 'bu-010' },
  { id: 'acc-105', name: 'Solventum', business_unit_id: 'bu-010' },
  { id: 'acc-106', name: 'SPX Flow', business_unit_id: 'bu-010' },
  { id: 'acc-107', name: 'Sudarshan', business_unit_id: 'bu-010' },
  { id: 'acc-108', name: 'TE CONNECTIVITY', business_unit_id: 'bu-010' },
  { id: 'acc-109', name: 'Tenneco', business_unit_id: 'bu-010' },
  { id: 'acc-110', name: 'Unidentified - IM & AD', business_unit_id: 'bu-010' },
  {
    id: 'acc-111',
    name: 'Unidentified - IMS - GE',
    business_unit_id: 'bu-010',
  },
  { id: 'acc-112', name: 'Veolia', business_unit_id: 'bu-010' },
  { id: 'acc-113', name: 'Yokogawa Electric', business_unit_id: 'bu-010' },

  // Retail Accounts
  { id: 'acc-114', name: 'AEON DELIGHT CO., LTD.', business_unit_id: 'bu-011' },
  { id: 'acc-115', name: 'MCDONALDS', business_unit_id: 'bu-011' },
  { id: 'acc-116', name: 'NISSEN', business_unit_id: 'bu-011' },
  { id: 'acc-117', name: 'RAKUTEN', business_unit_id: 'bu-011' },
]
