import type { Project } from '@/entity-types/project'

export const projects: Project[] = [
  {
    id: 'proj-001',
    name: 'NOMURA Digital Transformation',
    service_line: 'Consulting',
    process: null,
    project_type: 'Delivery',
    tech_solution: 'SAP',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: 'Signed',
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: 120000,
    revenue: 150000,
    estimated_hours: 800,
    initial_hours: 600,
    actual_hours: null,
    one_time_cost: null,
    potential_fte_saving: null,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Execution',
    status: 'Active',
    status_reason: '',
    start_date: '2024-01-15',
    end_date: '2025-06-30',
    theme_id: null,
    business_unit_id: 'bu-001',
    account_id: 'acc-001',
  },
  {
    id: 'proj-002',
    name: 'Coca Cola Bottlers Japan — Process Optimization',
    service_line: null,
    process: 'Order to Cash',
    project_type: 'Internal',
    tech_solution: null,
    progear_id: 'PG-002',
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: null,
    bb: null,
    digital_manager: null,
    is_billiable: false,
    is_external: false,
    cost: 45000,
    revenue: null,
    estimated_hours: 400,
    initial_hours: 400,
    actual_hours: 380,
    one_time_cost: 20000,
    potential_fte_saving: 2,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Discovery',
    status: 'Planning',
    status_reason: '',
    start_date: '2024-09-01',
    end_date: null,
    theme_id: null,
    business_unit_id: 'bu-002',
    account_id: 'acc-006',
  },
  {
    id: 'proj-003',
    name: 'Consumer Goods Analytics PoC',
    service_line: 'Analytics',
    process: null,
    project_type: 'Proof of Concept',
    tech_solution: 'Cloud',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: 'Pending',
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: null,
    revenue: null,
    estimated_hours: 200,
    initial_hours: 200,
    actual_hours: null,
    one_time_cost: null,
    potential_fte_saving: null,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Proposal',
    status: 'Draft',
    status_reason: '',
    start_date: null,
    end_date: null,
    theme_id: null,
    business_unit_id: 'bu-003',
    account_id: 'acc-009',
  },
  {
    id: 'proj-004',
    name: 'BUPA Healthcare Integration',
    service_line: 'Integration',
    process: null,
    project_type: 'Delivery',
    tech_solution: 'API',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: 'Signed',
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: 280000,
    revenue: 320000,
    estimated_hours: 1200,
    initial_hours: 1000,
    actual_hours: 950,
    one_time_cost: 50000,
    potential_fte_saving: 3,
    actual_fte_saving: 2,
    actual_released_hc: null,
    in_scope_fte: 5,
    business_impact: 4,
    stage: 'Execution',
    status: 'Active',
    status_reason: '',
    start_date: '2023-06-01',
    end_date: '2025-03-31',
    theme_id: null,
    business_unit_id: 'bu-005',
    account_id: 'acc-024',
  },
  {
    id: 'proj-005',
    name: 'Amazon Software Platform',
    service_line: null,
    process: null,
    project_type: 'Delivery',
    tech_solution: 'Custom',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: 'Signed',
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: 500000,
    revenue: 600000,
    estimated_hours: 2500,
    initial_hours: 2400,
    actual_hours: 2300,
    one_time_cost: 100000,
    potential_fte_saving: 5,
    actual_fte_saving: 4,
    actual_released_hc: 2,
    in_scope_fte: 10,
    business_impact: 8,
    stage: 'Closed',
    status: 'Completed',
    status_reason: 'Delivered on time',
    start_date: '2022-04-01',
    end_date: '2024-10-31',
    theme_id: null,
    business_unit_id: 'bu-007',
    account_id: 'acc-039',
  },
  {
    id: 'proj-006',
    name: 'Lifesciences Regulatory Reporting',
    service_line: 'Compliance',
    process: 'Record to Report',
    project_type: 'Internal',
    tech_solution: null,
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: null,
    bb: null,
    digital_manager: null,
    is_billiable: false,
    is_external: false,
    cost: 75000,
    revenue: null,
    estimated_hours: 600,
    initial_hours: 500,
    actual_hours: null,
    one_time_cost: null,
    potential_fte_saving: 1,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Execution',
    status: 'Active',
    status_reason: '',
    start_date: '2024-07-01',
    end_date: '2025-12-31',
    theme_id: null,
    business_unit_id: 'bu-009',
    account_id: 'acc-056',
  },
  {
    id: 'proj-007',
    name: 'Manufacturing 3M — Automation',
    service_line: 'Automation',
    process: null,
    project_type: 'Delivery',
    tech_solution: 'RPA',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: 'Pending',
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: null,
    revenue: null,
    estimated_hours: 900,
    initial_hours: 900,
    actual_hours: null,
    one_time_cost: null,
    potential_fte_saving: null,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Proposal',
    status: 'Planning',
    status_reason: '',
    start_date: null,
    end_date: null,
    theme_id: null,
    business_unit_id: 'bu-010',
    account_id: 'acc-074',
  },
  {
    id: 'proj-008',
    name: "McDonald's Retail Analytics",
    service_line: 'Analytics',
    process: null,
    project_type: 'Proof of Concept',
    tech_solution: 'Data Lake',
    progear_id: null,
    ops_mentor: null,
    sdl_name: null,
    sign_off_status: null,
    bb: null,
    digital_manager: null,
    is_billiable: true,
    is_external: true,
    cost: 35000,
    revenue: 40000,
    estimated_hours: 250,
    initial_hours: 250,
    actual_hours: 240,
    one_time_cost: 15000,
    potential_fte_saving: null,
    actual_fte_saving: null,
    actual_released_hc: null,
    in_scope_fte: null,
    business_impact: null,
    stage: 'Execution',
    status: 'Active',
    status_reason: '',
    start_date: '2024-11-01',
    end_date: '2025-02-28',
    theme_id: null,
    business_unit_id: 'bu-011',
    account_id: 'acc-115',
  },
]
