import type { TimeEntry } from '@/entity-types/time-entry'

export const timeEntries: TimeEntry[] = [
  {
    id: 'te-001',
    activity: 'Local solution implementation',
    hours: 4,
    comments: 'Worked on NOMURA Digital Transformation project',
    theme_id: 'theme-001',
    has_project: true,
    project_id: 'proj-001',
    date: '2026-03-09',
  },
  {
    id: 'te-002',
    activity: 'As‑Is Process Understanding',
    hours: 2,
    comments: 'Client meeting for Coca-Cola project',
    theme_id: 'theme-002',
    has_project: true,
    project_id: 'proj-002',
    date: '2026-03-09',
  },
  {
    id: 'te-003',
    activity: 'Workshop Facilitation',
    hours: 3,
    comments: 'Research on GenAI solutions for Consumer Goods Analytics',
    theme_id: 'theme-003',
    has_project: true,
    project_id: 'proj-003',
    date: '2026-03-09',
  },
  {
    id: 'te-004',
    activity: 'Admin works(Reporting, system upload, etc)',
    hours: 1,
    comments: 'Weekly status report',
    theme_id: 'theme-009',
    has_project: false,
    project_id: null,
    date: '2026-03-09',
  },
  {
    id: 'te-005',
    activity: 'UAT Execution & Monitoring',
    hours: 3,
    comments: 'UAT testing for Lifesciences Regulatory Reporting',
    theme_id: 'theme-004',
    has_project: true,
    project_id: 'proj-006',
    date: '2026-03-09',
  },
  {
    id: 'te-006',
    activity: 'To‑Be Design & Finalization',
    hours: 2.5,
    comments: 'Design phase for Manufacturing 3M Automation',
    theme_id: 'theme-001',
    has_project: true,
    project_id: 'proj-007',
    date: '2026-03-08',
  },
  {
    id: 'te-007',
    activity: 'Data Collection & Analysis',
    hours: 1.5,
    comments: 'Analysis for McDonalds Retail Analytics',
    theme_id: 'theme-002',
    has_project: true,
    project_id: 'proj-008',
    date: '2026-03-08',
  },
  // March 10, 2026
  {
    id: 'te-008',
    activity: 'Local solution implementation',
    hours: 3.5,
    comments: 'Development work on NOMURA Digital Transformation',
    theme_id: 'theme-001',
    has_project: true,
    project_id: 'proj-001',
    date: '2026-03-10',
  },
  {
    id: 'te-009',
    activity: 'As‑Is Process Understanding',
    hours: 2,
    comments: 'Process analysis for Coca-Cola Bottlers Japan',
    theme_id: 'theme-002',
    has_project: true,
    project_id: 'proj-002',
    date: '2026-03-10',
  },
  {
    id: 'te-010',
    activity: 'Data Collection & Analysis',
    hours: 1.5,
    comments: 'Data gathering for Consumer Goods Analytics PoC',
    theme_id: 'theme-003',
    has_project: true,
    project_id: 'proj-003',
    date: '2026-03-10',
  },
  {
    id: 'te-011',
    activity: 'Training & Knowledge Transfer',
    hours: 2,
    comments: 'Team training on new automation tools',
    theme_id: 'theme-006',
    has_project: false,
    project_id: null,
    date: '2026-03-10',
  },
  {
    id: 'te-012',
    activity: 'UAT Execution & Monitoring',
    hours: 4,
    comments: 'UAT testing for BUPA Healthcare Integration',
    theme_id: 'theme-004',
    has_project: true,
    project_id: 'proj-004',
    date: '2026-03-10',
  },
]
