import type { TimeEntry } from '@/entity-types/time-entry'

export const timeEntries: TimeEntry[] = [
  {
    id: 'te-001',
    activity: 'Development',
    hours: 4,
    comments: 'Worked on NOMURA Digital Transformation project',
    theme_id: 'theme-001',
    has_project: true,
    project_id: 'proj-001',
    date: '2026-03-09',
  },
  {
    id: 'te-002',
    activity: 'Meeting',
    hours: 2,
    comments: 'Client meeting for Coca-Cola project',
    theme_id: 'theme-002',
    has_project: true,
    project_id: 'proj-002',
    date: '2026-03-09',
  },
  {
    id: 'te-003',
    activity: 'Research',
    hours: 3,
    comments: 'Research on GenAI solutions for Consumer Goods Analytics',
    theme_id: 'theme-003',
    has_project: true,
    project_id: 'proj-003',
    date: '2026-03-09',
  },
  {
    id: 'te-004',
    activity: 'Admin',
    hours: 1,
    comments: 'Weekly status report',
    theme_id: null,
    has_project: false,
    project_id: null,
    date: '2026-03-09',
  },
  {
    id: 'te-005',
    activity: 'Testing',
    hours: 3,
    comments: 'UAT testing for Lifesciences Regulatory Reporting',
    theme_id: 'theme-004',
    has_project: true,
    project_id: 'proj-006',
    date: '2026-03-09',
  },
]
